name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'master'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email jlpuertov@gmail.com 
          # git config --global user.name Jose Puerto
          git config --global user.email jlpuertov@gmail.com 
          git config --global user.name Jose Puerto
          git status
          # change this remote url for examle your remote url is https://github.com/puertojose/viena_kalevala_game.git then the following:
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/puertojose/viena_kalevala_game.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
